// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: siplicity/v1/siplicity.proto

package siplicityv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GraphType int32

const (
	GraphType_GRAPH_TYPE_UNSPECIFIED GraphType = 0
	GraphType_GRAPH_TYPE_INPUT       GraphType = 1
	GraphType_GRAPH_TYPE_OUTPUT      GraphType = 2
	GraphType_GRAPH_TYPE_DUPLICATE   GraphType = 3
)

// Enum value maps for GraphType.
var (
	GraphType_name = map[int32]string{
		0: "GRAPH_TYPE_UNSPECIFIED",
		1: "GRAPH_TYPE_INPUT",
		2: "GRAPH_TYPE_OUTPUT",
		3: "GRAPH_TYPE_DUPLICATE",
	}
	GraphType_value = map[string]int32{
		"GRAPH_TYPE_UNSPECIFIED": 0,
		"GRAPH_TYPE_INPUT":       1,
		"GRAPH_TYPE_OUTPUT":      2,
		"GRAPH_TYPE_DUPLICATE":   3,
	}
)

func (x GraphType) Enum() *GraphType {
	p := new(GraphType)
	*p = x
	return p
}

func (x GraphType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GraphType) Descriptor() protoreflect.EnumDescriptor {
	return file_siplicity_v1_siplicity_proto_enumTypes[0].Descriptor()
}

func (GraphType) Type() protoreflect.EnumType {
	return &file_siplicity_v1_siplicity_proto_enumTypes[0]
}

func (x GraphType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GraphType.Descriptor instead.
func (GraphType) EnumDescriptor() ([]byte, []int) {
	return file_siplicity_v1_siplicity_proto_rawDescGZIP(), []int{0}
}

type RecordType int32

const (
	RecordType_RECORD_TYPE_UNSPECIFIED       RecordType = 0
	RecordType_RECORD_TYPE_ROOT              RecordType = 1
	RecordType_RECORD_TYPE_FILE              RecordType = 2
	RecordType_RECORD_TYPE_VIRTUAL_FILE      RecordType = 3
	RecordType_RECORD_TYPE_DIRECTORY         RecordType = 4
	RecordType_RECORD_TYPE_VIRTUAL_DIRECTORY RecordType = 5
	RecordType_RECORD_TYPE_ARCHIVE           RecordType = 6
	RecordType_RECORD_TYPE_VIRTUAL_ARCHIVE   RecordType = 7
)

// Enum value maps for RecordType.
var (
	RecordType_name = map[int32]string{
		0: "RECORD_TYPE_UNSPECIFIED",
		1: "RECORD_TYPE_ROOT",
		2: "RECORD_TYPE_FILE",
		3: "RECORD_TYPE_VIRTUAL_FILE",
		4: "RECORD_TYPE_DIRECTORY",
		5: "RECORD_TYPE_VIRTUAL_DIRECTORY",
		6: "RECORD_TYPE_ARCHIVE",
		7: "RECORD_TYPE_VIRTUAL_ARCHIVE",
	}
	RecordType_value = map[string]int32{
		"RECORD_TYPE_UNSPECIFIED":       0,
		"RECORD_TYPE_ROOT":              1,
		"RECORD_TYPE_FILE":              2,
		"RECORD_TYPE_VIRTUAL_FILE":      3,
		"RECORD_TYPE_DIRECTORY":         4,
		"RECORD_TYPE_VIRTUAL_DIRECTORY": 5,
		"RECORD_TYPE_ARCHIVE":           6,
		"RECORD_TYPE_VIRTUAL_ARCHIVE":   7,
	}
)

func (x RecordType) Enum() *RecordType {
	p := new(RecordType)
	*p = x
	return p
}

func (x RecordType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RecordType) Descriptor() protoreflect.EnumDescriptor {
	return file_siplicity_v1_siplicity_proto_enumTypes[1].Descriptor()
}

func (RecordType) Type() protoreflect.EnumType {
	return &file_siplicity_v1_siplicity_proto_enumTypes[1]
}

func (x RecordType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RecordType.Descriptor instead.
func (RecordType) EnumDescriptor() ([]byte, []int) {
	return file_siplicity_v1_siplicity_proto_rawDescGZIP(), []int{1}
}

type GetStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int32 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_siplicity_v1_siplicity_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_siplicity_v1_siplicity_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_siplicity_v1_siplicity_proto_rawDescGZIP(), []int{0}
}

func (x *GetStatusRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type GetStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Done bool `protobuf:"varint,1,opt,name=done,proto3" json:"done,omitempty"`
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_siplicity_v1_siplicity_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_siplicity_v1_siplicity_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_siplicity_v1_siplicity_proto_rawDescGZIP(), []int{1}
}

func (x *GetStatusResponse) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

type PutFilePathRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *PutFilePathRequest) Reset() {
	*x = PutFilePathRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_siplicity_v1_siplicity_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutFilePathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutFilePathRequest) ProtoMessage() {}

func (x *PutFilePathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_siplicity_v1_siplicity_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutFilePathRequest.ProtoReflect.Descriptor instead.
func (*PutFilePathRequest) Descriptor() ([]byte, []int) {
	return file_siplicity_v1_siplicity_proto_rawDescGZIP(), []int{2}
}

func (x *PutFilePathRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type PutFilePathResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int32 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *PutFilePathResponse) Reset() {
	*x = PutFilePathResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_siplicity_v1_siplicity_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutFilePathResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutFilePathResponse) ProtoMessage() {}

func (x *PutFilePathResponse) ProtoReflect() protoreflect.Message {
	mi := &file_siplicity_v1_siplicity_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutFilePathResponse.ProtoReflect.Descriptor instead.
func (*PutFilePathResponse) Descriptor() ([]byte, []int) {
	return file_siplicity_v1_siplicity_proto_rawDescGZIP(), []int{3}
}

func (x *PutFilePathResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type Selection struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id []int32 `protobuf:"varint,1,rep,packed,name=id,proto3" json:"id,omitempty"`
}

func (x *Selection) Reset() {
	*x = Selection{}
	if protoimpl.UnsafeEnabled {
		mi := &file_siplicity_v1_siplicity_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Selection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Selection) ProtoMessage() {}

func (x *Selection) ProtoReflect() protoreflect.Message {
	mi := &file_siplicity_v1_siplicity_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Selection.ProtoReflect.Descriptor instead.
func (*Selection) Descriptor() ([]byte, []int) {
	return file_siplicity_v1_siplicity_proto_rawDescGZIP(), []int{4}
}

func (x *Selection) GetId() []int32 {
	if x != nil {
		return x.Id
	}
	return nil
}

type PutJobRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Selection *Selection `protobuf:"bytes,1,opt,name=selection,proto3,oneof" json:"selection,omitempty"`
	Filter    *string    `protobuf:"bytes,2,opt,name=filter,proto3,oneof" json:"filter,omitempty"`
	Action    string     `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
}

func (x *PutJobRequest) Reset() {
	*x = PutJobRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_siplicity_v1_siplicity_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutJobRequest) ProtoMessage() {}

func (x *PutJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_siplicity_v1_siplicity_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutJobRequest.ProtoReflect.Descriptor instead.
func (*PutJobRequest) Descriptor() ([]byte, []int) {
	return file_siplicity_v1_siplicity_proto_rawDescGZIP(), []int{5}
}

func (x *PutJobRequest) GetSelection() *Selection {
	if x != nil {
		return x.Selection
	}
	return nil
}

func (x *PutJobRequest) GetFilter() string {
	if x != nil && x.Filter != nil {
		return *x.Filter
	}
	return ""
}

func (x *PutJobRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type PutJobResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int32 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *PutJobResponse) Reset() {
	*x = PutJobResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_siplicity_v1_siplicity_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutJobResponse) ProtoMessage() {}

func (x *PutJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_siplicity_v1_siplicity_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutJobResponse.ProtoReflect.Descriptor instead.
func (*PutJobResponse) Descriptor() ([]byte, []int) {
	return file_siplicity_v1_siplicity_proto_rawDescGZIP(), []int{6}
}

func (x *PutJobResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type CountRecordsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     *int32     `protobuf:"varint,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	Graph  *GraphType `protobuf:"varint,2,opt,name=graph,proto3,enum=siplicity.v1.GraphType,oneof" json:"graph,omitempty"`
	Filter *string    `protobuf:"bytes,3,opt,name=filter,proto3,oneof" json:"filter,omitempty"`
}

func (x *CountRecordsRequest) Reset() {
	*x = CountRecordsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_siplicity_v1_siplicity_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CountRecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountRecordsRequest) ProtoMessage() {}

func (x *CountRecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_siplicity_v1_siplicity_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountRecordsRequest.ProtoReflect.Descriptor instead.
func (*CountRecordsRequest) Descriptor() ([]byte, []int) {
	return file_siplicity_v1_siplicity_proto_rawDescGZIP(), []int{7}
}

func (x *CountRecordsRequest) GetId() int32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *CountRecordsRequest) GetGraph() GraphType {
	if x != nil && x.Graph != nil {
		return *x.Graph
	}
	return GraphType_GRAPH_TYPE_UNSPECIFIED
}

func (x *CountRecordsRequest) GetFilter() string {
	if x != nil && x.Filter != nil {
		return *x.Filter
	}
	return ""
}

type CountRecordsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int32 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *CountRecordsResponse) Reset() {
	*x = CountRecordsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_siplicity_v1_siplicity_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CountRecordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountRecordsResponse) ProtoMessage() {}

func (x *CountRecordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_siplicity_v1_siplicity_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountRecordsResponse.ProtoReflect.Descriptor instead.
func (*CountRecordsResponse) Descriptor() ([]byte, []int) {
	return file_siplicity_v1_siplicity_proto_rawDescGZIP(), []int{8}
}

func (x *CountRecordsResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type FieldPath struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entries []*FieldPath_Entry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
}

func (x *FieldPath) Reset() {
	*x = FieldPath{}
	if protoimpl.UnsafeEnabled {
		mi := &file_siplicity_v1_siplicity_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FieldPath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldPath) ProtoMessage() {}

func (x *FieldPath) ProtoReflect() protoreflect.Message {
	mi := &file_siplicity_v1_siplicity_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldPath.ProtoReflect.Descriptor instead.
func (*FieldPath) Descriptor() ([]byte, []int) {
	return file_siplicity_v1_siplicity_proto_rawDescGZIP(), []int{9}
}

func (x *FieldPath) GetEntries() []*FieldPath_Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type ListRecordsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      *int32       `protobuf:"varint,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	Graph   *GraphType   `protobuf:"varint,2,opt,name=graph,proto3,enum=siplicity.v1.GraphType,oneof" json:"graph,omitempty"`
	Filter  *string      `protobuf:"bytes,3,opt,name=filter,proto3,oneof" json:"filter,omitempty"`
	Display *FieldPath   `protobuf:"bytes,4,opt,name=display,proto3,oneof" json:"display,omitempty"`
	Fields  []*FieldPath `protobuf:"bytes,5,rep,name=fields,proto3" json:"fields,omitempty"`
}

func (x *ListRecordsRequest) Reset() {
	*x = ListRecordsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_siplicity_v1_siplicity_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListRecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecordsRequest) ProtoMessage() {}

func (x *ListRecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_siplicity_v1_siplicity_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecordsRequest.ProtoReflect.Descriptor instead.
func (*ListRecordsRequest) Descriptor() ([]byte, []int) {
	return file_siplicity_v1_siplicity_proto_rawDescGZIP(), []int{10}
}

func (x *ListRecordsRequest) GetId() int32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *ListRecordsRequest) GetGraph() GraphType {
	if x != nil && x.Graph != nil {
		return *x.Graph
	}
	return GraphType_GRAPH_TYPE_UNSPECIFIED
}

func (x *ListRecordsRequest) GetFilter() string {
	if x != nil && x.Filter != nil {
		return *x.Filter
	}
	return ""
}

func (x *ListRecordsRequest) GetDisplay() *FieldPath {
	if x != nil {
		return x.Display
	}
	return nil
}

func (x *ListRecordsRequest) GetFields() []*FieldPath {
	if x != nil {
		return x.Fields
	}
	return nil
}

type Field struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Value     string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Field) Reset() {
	*x = Field{}
	if protoimpl.UnsafeEnabled {
		mi := &file_siplicity_v1_siplicity_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Field) ProtoMessage() {}

func (x *Field) ProtoReflect() protoreflect.Message {
	mi := &file_siplicity_v1_siplicity_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Field.ProtoReflect.Descriptor instead.
func (*Field) Descriptor() ([]byte, []int) {
	return file_siplicity_v1_siplicity_proto_rawDescGZIP(), []int{11}
}

func (x *Field) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Field) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Field) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ListRecordsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Typ      RecordType             `protobuf:"varint,2,opt,name=typ,proto3,enum=siplicity.v1.RecordType" json:"typ,omitempty"`
	Name     string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Fields   []*Field               `protobuf:"bytes,4,rep,name=fields,proto3" json:"fields,omitempty"`
	Children []*ListRecordsResponse `protobuf:"bytes,5,rep,name=children,proto3" json:"children,omitempty"`
}

func (x *ListRecordsResponse) Reset() {
	*x = ListRecordsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_siplicity_v1_siplicity_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListRecordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecordsResponse) ProtoMessage() {}

func (x *ListRecordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_siplicity_v1_siplicity_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecordsResponse.ProtoReflect.Descriptor instead.
func (*ListRecordsResponse) Descriptor() ([]byte, []int) {
	return file_siplicity_v1_siplicity_proto_rawDescGZIP(), []int{12}
}

func (x *ListRecordsResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ListRecordsResponse) GetTyp() RecordType {
	if x != nil {
		return x.Typ
	}
	return RecordType_RECORD_TYPE_UNSPECIFIED
}

func (x *ListRecordsResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListRecordsResponse) GetFields() []*Field {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *ListRecordsResponse) GetChildren() []*ListRecordsResponse {
	if x != nil {
		return x.Children
	}
	return nil
}

type GetRecordRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetRecordRequest) Reset() {
	*x = GetRecordRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_siplicity_v1_siplicity_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecordRequest) ProtoMessage() {}

func (x *GetRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_siplicity_v1_siplicity_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecordRequest.ProtoReflect.Descriptor instead.
func (*GetRecordRequest) Descriptor() ([]byte, []int) {
	return file_siplicity_v1_siplicity_proto_rawDescGZIP(), []int{13}
}

func (x *GetRecordRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Metadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Field    *Field      `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Children []*Metadata `protobuf:"bytes,2,rep,name=children,proto3" json:"children,omitempty"`
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_siplicity_v1_siplicity_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_siplicity_v1_siplicity_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_siplicity_v1_siplicity_proto_rawDescGZIP(), []int{14}
}

func (x *Metadata) GetField() *Field {
	if x != nil {
		return x.Field
	}
	return nil
}

func (x *Metadata) GetChildren() []*Metadata {
	if x != nil {
		return x.Children
	}
	return nil
}

type GetRecordResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Typ      RecordType  `protobuf:"varint,1,opt,name=typ,proto3,enum=siplicity.v1.RecordType" json:"typ,omitempty"`
	Path     string      `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Size     int64       `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Metadata []*Metadata `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty"`
}

func (x *GetRecordResponse) Reset() {
	*x = GetRecordResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_siplicity_v1_siplicity_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecordResponse) ProtoMessage() {}

func (x *GetRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_siplicity_v1_siplicity_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecordResponse.ProtoReflect.Descriptor instead.
func (*GetRecordResponse) Descriptor() ([]byte, []int) {
	return file_siplicity_v1_siplicity_proto_rawDescGZIP(), []int{15}
}

func (x *GetRecordResponse) GetTyp() RecordType {
	if x != nil {
		return x.Typ
	}
	return RecordType_RECORD_TYPE_UNSPECIFIED
}

func (x *GetRecordResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *GetRecordResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GetRecordResponse) GetMetadata() []*Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type PutRecordRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     *int32             `protobuf:"varint,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	Graph  *GraphType         `protobuf:"varint,2,opt,name=graph,proto3,enum=siplicity.v1.GraphType,oneof" json:"graph,omitempty"`
	Record *GetRecordResponse `protobuf:"bytes,3,opt,name=record,proto3" json:"record,omitempty"`
}

func (x *PutRecordRequest) Reset() {
	*x = PutRecordRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_siplicity_v1_siplicity_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRecordRequest) ProtoMessage() {}

func (x *PutRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_siplicity_v1_siplicity_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRecordRequest.ProtoReflect.Descriptor instead.
func (*PutRecordRequest) Descriptor() ([]byte, []int) {
	return file_siplicity_v1_siplicity_proto_rawDescGZIP(), []int{16}
}

func (x *PutRecordRequest) GetId() int32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *PutRecordRequest) GetGraph() GraphType {
	if x != nil && x.Graph != nil {
		return *x.Graph
	}
	return GraphType_GRAPH_TYPE_UNSPECIFIED
}

func (x *PutRecordRequest) GetRecord() *GetRecordResponse {
	if x != nil {
		return x.Record
	}
	return nil
}

type PutRecordResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *PutRecordResponse) Reset() {
	*x = PutRecordResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_siplicity_v1_siplicity_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRecordResponse) ProtoMessage() {}

func (x *PutRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_siplicity_v1_siplicity_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRecordResponse.ProtoReflect.Descriptor instead.
func (*PutRecordResponse) Descriptor() ([]byte, []int) {
	return file_siplicity_v1_siplicity_proto_rawDescGZIP(), []int{17}
}

func (x *PutRecordResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateRecordRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int32              `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Record *GetRecordResponse `protobuf:"bytes,2,opt,name=record,proto3" json:"record,omitempty"`
}

func (x *UpdateRecordRequest) Reset() {
	*x = UpdateRecordRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_siplicity_v1_siplicity_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRecordRequest) ProtoMessage() {}

func (x *UpdateRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_siplicity_v1_siplicity_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRecordRequest.ProtoReflect.Descriptor instead.
func (*UpdateRecordRequest) Descriptor() ([]byte, []int) {
	return file_siplicity_v1_siplicity_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateRecordRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateRecordRequest) GetRecord() *GetRecordResponse {
	if x != nil {
		return x.Record
	}
	return nil
}

type UpdateRecordResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateRecordResponse) Reset() {
	*x = UpdateRecordResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_siplicity_v1_siplicity_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRecordResponse) ProtoMessage() {}

func (x *UpdateRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_siplicity_v1_siplicity_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRecordResponse.ProtoReflect.Descriptor instead.
func (*UpdateRecordResponse) Descriptor() ([]byte, []int) {
	return file_siplicity_v1_siplicity_proto_rawDescGZIP(), []int{19}
}

type UpdateFieldRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int32      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Path      *FieldPath `protobuf:"bytes,2,opt,name=path,proto3,oneof" json:"path,omitempty"`
	Overwrite *bool      `protobuf:"varint,3,opt,name=overwrite,proto3,oneof" json:"overwrite,omitempty"`
	Field     *Field     `protobuf:"bytes,4,opt,name=field,proto3" json:"field,omitempty"`
}

func (x *UpdateFieldRequest) Reset() {
	*x = UpdateFieldRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_siplicity_v1_siplicity_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateFieldRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFieldRequest) ProtoMessage() {}

func (x *UpdateFieldRequest) ProtoReflect() protoreflect.Message {
	mi := &file_siplicity_v1_siplicity_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFieldRequest.ProtoReflect.Descriptor instead.
func (*UpdateFieldRequest) Descriptor() ([]byte, []int) {
	return file_siplicity_v1_siplicity_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateFieldRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateFieldRequest) GetPath() *FieldPath {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *UpdateFieldRequest) GetOverwrite() bool {
	if x != nil && x.Overwrite != nil {
		return *x.Overwrite
	}
	return false
}

func (x *UpdateFieldRequest) GetField() *Field {
	if x != nil {
		return x.Field
	}
	return nil
}

type UpdateFieldResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateFieldResponse) Reset() {
	*x = UpdateFieldResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_siplicity_v1_siplicity_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateFieldResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFieldResponse) ProtoMessage() {}

func (x *UpdateFieldResponse) ProtoReflect() protoreflect.Message {
	mi := &file_siplicity_v1_siplicity_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFieldResponse.ProtoReflect.Descriptor instead.
func (*UpdateFieldResponse) Descriptor() ([]byte, []int) {
	return file_siplicity_v1_siplicity_proto_rawDescGZIP(), []int{21}
}

type LinkRecordsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      *int32     `protobuf:"varint,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	Graph   GraphType  `protobuf:"varint,2,opt,name=graph,proto3,enum=siplicity.v1.GraphType" json:"graph,omitempty"`
	Origin  *GraphType `protobuf:"varint,3,opt,name=origin,proto3,enum=siplicity.v1.GraphType,oneof" json:"origin,omitempty"`
	Shift   *bool      `protobuf:"varint,4,opt,name=shift,proto3,oneof" json:"shift,omitempty"`
	Records *Selection `protobuf:"bytes,5,opt,name=records,proto3" json:"records,omitempty"`
}

func (x *LinkRecordsRequest) Reset() {
	*x = LinkRecordsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_siplicity_v1_siplicity_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LinkRecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkRecordsRequest) ProtoMessage() {}

func (x *LinkRecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_siplicity_v1_siplicity_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkRecordsRequest.ProtoReflect.Descriptor instead.
func (*LinkRecordsRequest) Descriptor() ([]byte, []int) {
	return file_siplicity_v1_siplicity_proto_rawDescGZIP(), []int{22}
}

func (x *LinkRecordsRequest) GetId() int32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *LinkRecordsRequest) GetGraph() GraphType {
	if x != nil {
		return x.Graph
	}
	return GraphType_GRAPH_TYPE_UNSPECIFIED
}

func (x *LinkRecordsRequest) GetOrigin() GraphType {
	if x != nil && x.Origin != nil {
		return *x.Origin
	}
	return GraphType_GRAPH_TYPE_UNSPECIFIED
}

func (x *LinkRecordsRequest) GetShift() bool {
	if x != nil && x.Shift != nil {
		return *x.Shift
	}
	return false
}

func (x *LinkRecordsRequest) GetRecords() *Selection {
	if x != nil {
		return x.Records
	}
	return nil
}

type LinkRecordsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LinkRecordsResponse) Reset() {
	*x = LinkRecordsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_siplicity_v1_siplicity_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LinkRecordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkRecordsResponse) ProtoMessage() {}

func (x *LinkRecordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_siplicity_v1_siplicity_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkRecordsResponse.ProtoReflect.Descriptor instead.
func (*LinkRecordsResponse) Descriptor() ([]byte, []int) {
	return file_siplicity_v1_siplicity_proto_rawDescGZIP(), []int{23}
}

type UnlinkRecordsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Graph   GraphType  `protobuf:"varint,1,opt,name=graph,proto3,enum=siplicity.v1.GraphType" json:"graph,omitempty"`
	Records *Selection `protobuf:"bytes,2,opt,name=records,proto3" json:"records,omitempty"`
}

func (x *UnlinkRecordsRequest) Reset() {
	*x = UnlinkRecordsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_siplicity_v1_siplicity_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnlinkRecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlinkRecordsRequest) ProtoMessage() {}

func (x *UnlinkRecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_siplicity_v1_siplicity_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlinkRecordsRequest.ProtoReflect.Descriptor instead.
func (*UnlinkRecordsRequest) Descriptor() ([]byte, []int) {
	return file_siplicity_v1_siplicity_proto_rawDescGZIP(), []int{24}
}

func (x *UnlinkRecordsRequest) GetGraph() GraphType {
	if x != nil {
		return x.Graph
	}
	return GraphType_GRAPH_TYPE_UNSPECIFIED
}

func (x *UnlinkRecordsRequest) GetRecords() *Selection {
	if x != nil {
		return x.Records
	}
	return nil
}

type UnlinkRecordsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UnlinkRecordsResponse) Reset() {
	*x = UnlinkRecordsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_siplicity_v1_siplicity_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnlinkRecordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlinkRecordsResponse) ProtoMessage() {}

func (x *UnlinkRecordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_siplicity_v1_siplicity_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlinkRecordsResponse.ProtoReflect.Descriptor instead.
func (*UnlinkRecordsResponse) Descriptor() ([]byte, []int) {
	return file_siplicity_v1_siplicity_proto_rawDescGZIP(), []int{25}
}

type ShutdownRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_siplicity_v1_siplicity_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_siplicity_v1_siplicity_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_siplicity_v1_siplicity_proto_rawDescGZIP(), []int{26}
}

type ShutdownResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ShutdownResponse) Reset() {
	*x = ShutdownResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_siplicity_v1_siplicity_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResponse) ProtoMessage() {}

func (x *ShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_siplicity_v1_siplicity_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResponse.ProtoReflect.Descriptor instead.
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return file_siplicity_v1_siplicity_proto_rawDescGZIP(), []int{27}
}

type FieldPath_Entry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace *string `protobuf:"bytes,1,opt,name=namespace,proto3,oneof" json:"namespace,omitempty"`
	Name      string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Index     *int32  `protobuf:"varint,3,opt,name=index,proto3,oneof" json:"index,omitempty"`
}

func (x *FieldPath_Entry) Reset() {
	*x = FieldPath_Entry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_siplicity_v1_siplicity_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FieldPath_Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldPath_Entry) ProtoMessage() {}

func (x *FieldPath_Entry) ProtoReflect() protoreflect.Message {
	mi := &file_siplicity_v1_siplicity_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldPath_Entry.ProtoReflect.Descriptor instead.
func (*FieldPath_Entry) Descriptor() ([]byte, []int) {
	return file_siplicity_v1_siplicity_proto_rawDescGZIP(), []int{9, 0}
}

func (x *FieldPath_Entry) GetNamespace() string {
	if x != nil && x.Namespace != nil {
		return *x.Namespace
	}
	return ""
}

func (x *FieldPath_Entry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FieldPath_Entry) GetIndex() int32 {
	if x != nil && x.Index != nil {
		return *x.Index
	}
	return 0
}

var File_siplicity_v1_siplicity_proto protoreflect.FileDescriptor

var file_siplicity_v1_siplicity_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x73, 0x69, 0x70, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x79, 0x2f, 0x76, 0x31, 0x2f, 0x73,
	0x69, 0x70, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c,
	0x73, 0x69, 0x70, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x76, 0x31, 0x22, 0x2a, 0x0a, 0x10,
	0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x27, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x64, 0x6f, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x64, 0x6f, 0x6e,
	0x65, 0x22, 0x28, 0x0a, 0x12, 0x50, 0x75, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x2d, 0x0a, 0x13, 0x50,
	0x75, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x1b, 0x0a, 0x09, 0x53, 0x65,
	0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x99, 0x01, 0x0a, 0x0d, 0x50, 0x75, 0x74, 0x4a,
	0x6f, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3a, 0x0a, 0x09, 0x73, 0x65, 0x6c,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x73,
	0x69, 0x70, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x6c, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x09, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x1b, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x88,
	0x01, 0x01, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x73,
	0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x66, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x22, 0x28, 0x0a, 0x0e, 0x50, 0x75, 0x74, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x97, 0x01,
	0x0a, 0x13, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x13, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x48, 0x00, 0x52, 0x02, 0x69, 0x64, 0x88, 0x01, 0x01, 0x12, 0x32, 0x0a, 0x05, 0x67, 0x72,
	0x61, 0x70, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x73, 0x69, 0x70, 0x6c,
	0x69, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x72, 0x61, 0x70, 0x68, 0x54, 0x79,
	0x70, 0x65, 0x48, 0x01, 0x52, 0x05, 0x67, 0x72, 0x61, 0x70, 0x68, 0x88, 0x01, 0x01, 0x12, 0x1b,
	0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02,
	0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x88, 0x01, 0x01, 0x42, 0x05, 0x0a, 0x03, 0x5f,
	0x69, 0x64, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x67, 0x72, 0x61, 0x70, 0x68, 0x42, 0x09, 0x0a, 0x07,
	0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x22, 0x2c, 0x0a, 0x14, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0xb7, 0x01, 0x0a, 0x09, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x50,
	0x61, 0x74, 0x68, 0x12, 0x37, 0x0a, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x73, 0x69, 0x70, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x79,
	0x2e, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x50, 0x61, 0x74, 0x68, 0x2e, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x1a, 0x71, 0x0a, 0x05,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x21, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x88, 0x01, 0x01, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x05,
	0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x48, 0x01, 0x52, 0x05, 0x69,
	0x6e, 0x64, 0x65, 0x78, 0x88, 0x01, 0x01, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x22,
	0x8b, 0x02, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x13, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x48, 0x00, 0x52, 0x02, 0x69, 0x64, 0x88, 0x01, 0x01, 0x12, 0x32, 0x0a, 0x05, 0x67,
	0x72, 0x61, 0x70, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x73, 0x69, 0x70,
	0x6c, 0x69, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x72, 0x61, 0x70, 0x68, 0x54,
	0x79, 0x70, 0x65, 0x48, 0x01, 0x52, 0x05, 0x67, 0x72, 0x61, 0x70, 0x68, 0x88, 0x01, 0x01, 0x12,
	0x1b, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x02, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x88, 0x01, 0x01, 0x12, 0x36, 0x0a, 0x07,
	0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e,
	0x73, 0x69, 0x70, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x50, 0x61, 0x74, 0x68, 0x48, 0x03, 0x52, 0x07, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61,
	0x79, 0x88, 0x01, 0x01, 0x12, 0x2f, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x05,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x73, 0x69, 0x70, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x79,
	0x2e, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x50, 0x61, 0x74, 0x68, 0x52, 0x06, 0x66,
	0x69, 0x65, 0x6c, 0x64, 0x73, 0x42, 0x05, 0x0a, 0x03, 0x5f, 0x69, 0x64, 0x42, 0x08, 0x0a, 0x06,
	0x5f, 0x67, 0x72, 0x61, 0x70, 0x68, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x22, 0x4f, 0x0a,
	0x05, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0xd1,
	0x01, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2a, 0x0a, 0x03, 0x74, 0x79, 0x70, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x73, 0x69, 0x70, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x79, 0x2e,
	0x76, 0x31, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x54, 0x79, 0x70, 0x65, 0x52, 0x03, 0x74,
	0x79, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2b, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x69, 0x70, 0x6c, 0x69, 0x63, 0x69,
	0x74, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x06, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x73, 0x12, 0x3d, 0x0a, 0x08, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e, 0x18,
	0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x73, 0x69, 0x70, 0x6c, 0x69, 0x63, 0x69, 0x74,
	0x79, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x72,
	0x65, 0x6e, 0x22, 0x22, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x69, 0x0a, 0x08, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x12, 0x29, 0x0a, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x13, 0x2e, 0x73, 0x69, 0x70, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x76, 0x31,
	0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x32, 0x0a,
	0x08, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x73, 0x69, 0x70, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x08, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x72, 0x65,
	0x6e, 0x22, 0x9b, 0x01, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x03, 0x74, 0x79, 0x70, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x73, 0x69, 0x70, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x79,
	0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x54, 0x79, 0x70, 0x65, 0x52, 0x03,
	0x74, 0x79, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x32, 0x0a, 0x08, 0x6d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x73, 0x69, 0x70, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x22,
	0xa5, 0x01, 0x0a, 0x10, 0x50, 0x75, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x13, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x48, 0x00, 0x52, 0x02, 0x69, 0x64, 0x88, 0x01, 0x01, 0x12, 0x32, 0x0a, 0x05, 0x67, 0x72, 0x61,
	0x70, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x73, 0x69, 0x70, 0x6c, 0x69,
	0x63, 0x69, 0x74, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x72, 0x61, 0x70, 0x68, 0x54, 0x79, 0x70,
	0x65, 0x48, 0x01, 0x52, 0x05, 0x67, 0x72, 0x61, 0x70, 0x68, 0x88, 0x01, 0x01, 0x12, 0x37, 0x0a,
	0x06, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e,
	0x73, 0x69, 0x70, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x06,
	0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x42, 0x05, 0x0a, 0x03, 0x5f, 0x69, 0x64, 0x42, 0x08, 0x0a,
	0x06, 0x5f, 0x67, 0x72, 0x61, 0x70, 0x68, 0x22, 0x23, 0x0a, 0x11, 0x50, 0x75, 0x74, 0x52, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x5e, 0x0a, 0x13,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x37, 0x0a, 0x06, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x73, 0x69, 0x70, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x79, 0x2e,
	0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x52, 0x06, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x22, 0x16, 0x0a, 0x14,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0xbb, 0x01, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46,
	0x69, 0x65, 0x6c, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x30, 0x0a, 0x04, 0x70,
	0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x73, 0x69, 0x70, 0x6c,
	0x69, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x50, 0x61,
	0x74, 0x68, 0x48, 0x00, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x88, 0x01, 0x01, 0x12, 0x21, 0x0a,
	0x09, 0x6f, 0x76, 0x65, 0x72, 0x77, 0x72, 0x69, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08,
	0x48, 0x01, 0x52, 0x09, 0x6f, 0x76, 0x65, 0x72, 0x77, 0x72, 0x69, 0x74, 0x65, 0x88, 0x01, 0x01,
	0x12, 0x29, 0x0a, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x73, 0x69, 0x70, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x46,
	0x69, 0x65, 0x6c, 0x64, 0x52, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x42, 0x07, 0x0a, 0x05, 0x5f,
	0x70, 0x61, 0x74, 0x68, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x6f, 0x76, 0x65, 0x72, 0x77, 0x72, 0x69,
	0x74, 0x65, 0x22, 0x15, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x69, 0x65, 0x6c,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0xf8, 0x01, 0x0a, 0x12, 0x4c, 0x69,
	0x6e, 0x6b, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x13, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x02,
	0x69, 0x64, 0x88, 0x01, 0x01, 0x12, 0x2d, 0x0a, 0x05, 0x67, 0x72, 0x61, 0x70, 0x68, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x73, 0x69, 0x70, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x79,
	0x2e, 0x76, 0x31, 0x2e, 0x47, 0x72, 0x61, 0x70, 0x68, 0x54, 0x79, 0x70, 0x65, 0x52, 0x05, 0x67,
	0x72, 0x61, 0x70, 0x68, 0x12, 0x34, 0x0a, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x73, 0x69, 0x70, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x79,
	0x2e, 0x76, 0x31, 0x2e, 0x47, 0x72, 0x61, 0x70, 0x68, 0x54, 0x79, 0x70, 0x65, 0x48, 0x01, 0x52,
	0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x19, 0x0a, 0x05, 0x73, 0x68,
	0x69, 0x66, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x48, 0x02, 0x52, 0x05, 0x73, 0x68, 0x69,
	0x66, 0x74, 0x88, 0x01, 0x01, 0x12, 0x31, 0x0a, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x73, 0x69, 0x70, 0x6c, 0x69, 0x63, 0x69,
	0x74, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x07, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x42, 0x05, 0x0a, 0x03, 0x5f, 0x69, 0x64, 0x42,
	0x09, 0x0a, 0x07, 0x5f, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x73,
	0x68, 0x69, 0x66, 0x74, 0x22, 0x15, 0x0a, 0x13, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x78, 0x0a, 0x14, 0x55,
	0x6e, 0x6c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x05, 0x67, 0x72, 0x61, 0x70, 0x68, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x17, 0x2e, 0x73, 0x69, 0x70, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x76,
	0x31, 0x2e, 0x47, 0x72, 0x61, 0x70, 0x68, 0x54, 0x79, 0x70, 0x65, 0x52, 0x05, 0x67, 0x72, 0x61,
	0x70, 0x68, 0x12, 0x31, 0x0a, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x73, 0x69, 0x70, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x79, 0x2e,
	0x76, 0x31, 0x2e, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x72, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x73, 0x22, 0x17, 0x0a, 0x15, 0x55, 0x6e, 0x6c, 0x69, 0x6e, 0x6b, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x11,
	0x0a, 0x0f, 0x53, 0x68, 0x75, 0x74, 0x64, 0x6f, 0x77, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x12, 0x0a, 0x10, 0x53, 0x68, 0x75, 0x74, 0x64, 0x6f, 0x77, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2a, 0x6e, 0x0a, 0x09, 0x47, 0x72, 0x61, 0x70, 0x68, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x1a, 0x0a, 0x16, 0x47, 0x52, 0x41, 0x50, 0x48, 0x5f, 0x54, 0x59, 0x50, 0x45,
	0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x14,
	0x0a, 0x10, 0x47, 0x52, 0x41, 0x50, 0x48, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x49, 0x4e, 0x50,
	0x55, 0x54, 0x10, 0x01, 0x12, 0x15, 0x0a, 0x11, 0x47, 0x52, 0x41, 0x50, 0x48, 0x5f, 0x54, 0x59,
	0x50, 0x45, 0x5f, 0x4f, 0x55, 0x54, 0x50, 0x55, 0x54, 0x10, 0x02, 0x12, 0x18, 0x0a, 0x14, 0x47,
	0x52, 0x41, 0x50, 0x48, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x44, 0x55, 0x50, 0x4c, 0x49, 0x43,
	0x41, 0x54, 0x45, 0x10, 0x03, 0x2a, 0xeb, 0x01, 0x0a, 0x0a, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x17, 0x52, 0x45, 0x43, 0x4f, 0x52, 0x44, 0x5f, 0x54,
	0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10,
	0x00, 0x12, 0x14, 0x0a, 0x10, 0x52, 0x45, 0x43, 0x4f, 0x52, 0x44, 0x5f, 0x54, 0x59, 0x50, 0x45,
	0x5f, 0x52, 0x4f, 0x4f, 0x54, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x52, 0x45, 0x43, 0x4f, 0x52,
	0x44, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x46, 0x49, 0x4c, 0x45, 0x10, 0x02, 0x12, 0x1c, 0x0a,
	0x18, 0x52, 0x45, 0x43, 0x4f, 0x52, 0x44, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x56, 0x49, 0x52,
	0x54, 0x55, 0x41, 0x4c, 0x5f, 0x46, 0x49, 0x4c, 0x45, 0x10, 0x03, 0x12, 0x19, 0x0a, 0x15, 0x52,
	0x45, 0x43, 0x4f, 0x52, 0x44, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x44, 0x49, 0x52, 0x45, 0x43,
	0x54, 0x4f, 0x52, 0x59, 0x10, 0x04, 0x12, 0x21, 0x0a, 0x1d, 0x52, 0x45, 0x43, 0x4f, 0x52, 0x44,
	0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x56, 0x49, 0x52, 0x54, 0x55, 0x41, 0x4c, 0x5f, 0x44, 0x49,
	0x52, 0x45, 0x43, 0x54, 0x4f, 0x52, 0x59, 0x10, 0x05, 0x12, 0x17, 0x0a, 0x13, 0x52, 0x45, 0x43,
	0x4f, 0x52, 0x44, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x41, 0x52, 0x43, 0x48, 0x49, 0x56, 0x45,
	0x10, 0x06, 0x12, 0x1f, 0x0a, 0x1b, 0x52, 0x45, 0x43, 0x4f, 0x52, 0x44, 0x5f, 0x54, 0x59, 0x50,
	0x45, 0x5f, 0x56, 0x49, 0x52, 0x54, 0x55, 0x41, 0x4c, 0x5f, 0x41, 0x52, 0x43, 0x48, 0x49, 0x56,
	0x45, 0x10, 0x07, 0x32, 0xfc, 0x07, 0x0a, 0x10, 0x53, 0x69, 0x70, 0x6c, 0x69, 0x63, 0x69, 0x74,
	0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4e, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1e, 0x2e, 0x73, 0x69, 0x70, 0x6c, 0x69, 0x63, 0x69, 0x74,
	0x79, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x73, 0x69, 0x70, 0x6c, 0x69, 0x63, 0x69, 0x74,
	0x79, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x54, 0x0a, 0x0b, 0x50, 0x75, 0x74, 0x46,
	0x69, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x20, 0x2e, 0x73, 0x69, 0x70, 0x6c, 0x69, 0x63,
	0x69, 0x74, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x75, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x50, 0x61,
	0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x73, 0x69, 0x70, 0x6c,
	0x69, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x75, 0x74, 0x46, 0x69, 0x6c, 0x65,
	0x50, 0x61, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x45,
	0x0a, 0x06, 0x50, 0x75, 0x74, 0x4a, 0x6f, 0x62, 0x12, 0x1b, 0x2e, 0x73, 0x69, 0x70, 0x6c, 0x69,
	0x63, 0x69, 0x74, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x75, 0x74, 0x4a, 0x6f, 0x62, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x73, 0x69, 0x70, 0x6c, 0x69, 0x63, 0x69, 0x74,
	0x79, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x75, 0x74, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x57, 0x0a, 0x0c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x21, 0x2e, 0x73, 0x69, 0x70, 0x6c, 0x69, 0x63, 0x69, 0x74,
	0x79, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x73, 0x69, 0x70, 0x6c, 0x69,
	0x63, 0x69, 0x74, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x54,
	0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x20, 0x2e,
	0x73, 0x69, 0x70, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x21, 0x2e, 0x73, 0x69, 0x70, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x4e, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x12, 0x1e, 0x2e, 0x73, 0x69, 0x70, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x76, 0x31,
	0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1f, 0x2e, 0x73, 0x69, 0x70, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x76, 0x31,
	0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x4e, 0x0a, 0x09, 0x50, 0x75, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x12, 0x1e, 0x2e, 0x73, 0x69, 0x70, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x76, 0x31,
	0x2e, 0x50, 0x75, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1f, 0x2e, 0x73, 0x69, 0x70, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x76, 0x31,
	0x2e, 0x50, 0x75, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x57, 0x0a, 0x0c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x12, 0x21, 0x2e, 0x73, 0x69, 0x70, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x79,
	0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x73, 0x69, 0x70, 0x6c, 0x69, 0x63,
	0x69, 0x74, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x54, 0x0a,
	0x0b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x20, 0x2e, 0x73,
	0x69, 0x70, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21,
	0x2e, 0x73, 0x69, 0x70, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x54, 0x0a, 0x0b, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x73, 0x12, 0x20, 0x2e, 0x73, 0x69, 0x70, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x76,
	0x31, 0x2e, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x73, 0x69, 0x70, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x79,
	0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5a, 0x0a, 0x0d, 0x55, 0x6e, 0x6c,
	0x69, 0x6e, 0x6b, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x22, 0x2e, 0x73, 0x69, 0x70,
	0x6c, 0x69, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x6e, 0x6c, 0x69, 0x6e, 0x6b,
	0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23,
	0x2e, 0x73, 0x69, 0x70, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x6e,
	0x6c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4b, 0x0a, 0x08, 0x53, 0x68, 0x75, 0x74, 0x64, 0x6f, 0x77,
	0x6e, 0x12, 0x1d, 0x2e, 0x73, 0x69, 0x70, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x76, 0x31,
	0x2e, 0x53, 0x68, 0x75, 0x74, 0x64, 0x6f, 0x77, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1e, 0x2e, 0x73, 0x69, 0x70, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x76, 0x31, 0x2e,
	0x53, 0x68, 0x75, 0x74, 0x64, 0x6f, 0x77, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x42, 0x83, 0x01, 0x0a, 0x10, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x69, 0x70, 0x6c, 0x69,
	0x63, 0x69, 0x74, 0x79, 0x2e, 0x76, 0x31, 0x42, 0x0e, 0x53, 0x69, 0x70, 0x6c, 0x69, 0x63, 0x69,
	0x74, 0x79, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x0e, 0x2e, 0x2f, 0x3b, 0x73, 0x69,
	0x70, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x79, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x53, 0x58, 0x58, 0xaa,
	0x02, 0x0c, 0x53, 0x69, 0x70, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x56, 0x31, 0xca, 0x02,
	0x0c, 0x53, 0x69, 0x70, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x79, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x18,
	0x53, 0x69, 0x70, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x79, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42,
	0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x0d, 0x53, 0x69, 0x70, 0x6c, 0x69,
	0x63, 0x69, 0x74, 0x79, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_siplicity_v1_siplicity_proto_rawDescOnce sync.Once
	file_siplicity_v1_siplicity_proto_rawDescData = file_siplicity_v1_siplicity_proto_rawDesc
)

func file_siplicity_v1_siplicity_proto_rawDescGZIP() []byte {
	file_siplicity_v1_siplicity_proto_rawDescOnce.Do(func() {
		file_siplicity_v1_siplicity_proto_rawDescData = protoimpl.X.CompressGZIP(file_siplicity_v1_siplicity_proto_rawDescData)
	})
	return file_siplicity_v1_siplicity_proto_rawDescData
}

var file_siplicity_v1_siplicity_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_siplicity_v1_siplicity_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_siplicity_v1_siplicity_proto_goTypes = []any{
	(GraphType)(0),                // 0: siplicity.v1.GraphType
	(RecordType)(0),               // 1: siplicity.v1.RecordType
	(*GetStatusRequest)(nil),      // 2: siplicity.v1.GetStatusRequest
	(*GetStatusResponse)(nil),     // 3: siplicity.v1.GetStatusResponse
	(*PutFilePathRequest)(nil),    // 4: siplicity.v1.PutFilePathRequest
	(*PutFilePathResponse)(nil),   // 5: siplicity.v1.PutFilePathResponse
	(*Selection)(nil),             // 6: siplicity.v1.Selection
	(*PutJobRequest)(nil),         // 7: siplicity.v1.PutJobRequest
	(*PutJobResponse)(nil),        // 8: siplicity.v1.PutJobResponse
	(*CountRecordsRequest)(nil),   // 9: siplicity.v1.CountRecordsRequest
	(*CountRecordsResponse)(nil),  // 10: siplicity.v1.CountRecordsResponse
	(*FieldPath)(nil),             // 11: siplicity.v1.FieldPath
	(*ListRecordsRequest)(nil),    // 12: siplicity.v1.ListRecordsRequest
	(*Field)(nil),                 // 13: siplicity.v1.Field
	(*ListRecordsResponse)(nil),   // 14: siplicity.v1.ListRecordsResponse
	(*GetRecordRequest)(nil),      // 15: siplicity.v1.GetRecordRequest
	(*Metadata)(nil),              // 16: siplicity.v1.Metadata
	(*GetRecordResponse)(nil),     // 17: siplicity.v1.GetRecordResponse
	(*PutRecordRequest)(nil),      // 18: siplicity.v1.PutRecordRequest
	(*PutRecordResponse)(nil),     // 19: siplicity.v1.PutRecordResponse
	(*UpdateRecordRequest)(nil),   // 20: siplicity.v1.UpdateRecordRequest
	(*UpdateRecordResponse)(nil),  // 21: siplicity.v1.UpdateRecordResponse
	(*UpdateFieldRequest)(nil),    // 22: siplicity.v1.UpdateFieldRequest
	(*UpdateFieldResponse)(nil),   // 23: siplicity.v1.UpdateFieldResponse
	(*LinkRecordsRequest)(nil),    // 24: siplicity.v1.LinkRecordsRequest
	(*LinkRecordsResponse)(nil),   // 25: siplicity.v1.LinkRecordsResponse
	(*UnlinkRecordsRequest)(nil),  // 26: siplicity.v1.UnlinkRecordsRequest
	(*UnlinkRecordsResponse)(nil), // 27: siplicity.v1.UnlinkRecordsResponse
	(*ShutdownRequest)(nil),       // 28: siplicity.v1.ShutdownRequest
	(*ShutdownResponse)(nil),      // 29: siplicity.v1.ShutdownResponse
	(*FieldPath_Entry)(nil),       // 30: siplicity.v1.FieldPath.Entry
}
var file_siplicity_v1_siplicity_proto_depIdxs = []int32{
	6,  // 0: siplicity.v1.PutJobRequest.selection:type_name -> siplicity.v1.Selection
	0,  // 1: siplicity.v1.CountRecordsRequest.graph:type_name -> siplicity.v1.GraphType
	30, // 2: siplicity.v1.FieldPath.entries:type_name -> siplicity.v1.FieldPath.Entry
	0,  // 3: siplicity.v1.ListRecordsRequest.graph:type_name -> siplicity.v1.GraphType
	11, // 4: siplicity.v1.ListRecordsRequest.display:type_name -> siplicity.v1.FieldPath
	11, // 5: siplicity.v1.ListRecordsRequest.fields:type_name -> siplicity.v1.FieldPath
	1,  // 6: siplicity.v1.ListRecordsResponse.typ:type_name -> siplicity.v1.RecordType
	13, // 7: siplicity.v1.ListRecordsResponse.fields:type_name -> siplicity.v1.Field
	14, // 8: siplicity.v1.ListRecordsResponse.children:type_name -> siplicity.v1.ListRecordsResponse
	13, // 9: siplicity.v1.Metadata.field:type_name -> siplicity.v1.Field
	16, // 10: siplicity.v1.Metadata.children:type_name -> siplicity.v1.Metadata
	1,  // 11: siplicity.v1.GetRecordResponse.typ:type_name -> siplicity.v1.RecordType
	16, // 12: siplicity.v1.GetRecordResponse.metadata:type_name -> siplicity.v1.Metadata
	0,  // 13: siplicity.v1.PutRecordRequest.graph:type_name -> siplicity.v1.GraphType
	17, // 14: siplicity.v1.PutRecordRequest.record:type_name -> siplicity.v1.GetRecordResponse
	17, // 15: siplicity.v1.UpdateRecordRequest.record:type_name -> siplicity.v1.GetRecordResponse
	11, // 16: siplicity.v1.UpdateFieldRequest.path:type_name -> siplicity.v1.FieldPath
	13, // 17: siplicity.v1.UpdateFieldRequest.field:type_name -> siplicity.v1.Field
	0,  // 18: siplicity.v1.LinkRecordsRequest.graph:type_name -> siplicity.v1.GraphType
	0,  // 19: siplicity.v1.LinkRecordsRequest.origin:type_name -> siplicity.v1.GraphType
	6,  // 20: siplicity.v1.LinkRecordsRequest.records:type_name -> siplicity.v1.Selection
	0,  // 21: siplicity.v1.UnlinkRecordsRequest.graph:type_name -> siplicity.v1.GraphType
	6,  // 22: siplicity.v1.UnlinkRecordsRequest.records:type_name -> siplicity.v1.Selection
	2,  // 23: siplicity.v1.SiplicityService.GetStatus:input_type -> siplicity.v1.GetStatusRequest
	4,  // 24: siplicity.v1.SiplicityService.PutFilePath:input_type -> siplicity.v1.PutFilePathRequest
	7,  // 25: siplicity.v1.SiplicityService.PutJob:input_type -> siplicity.v1.PutJobRequest
	9,  // 26: siplicity.v1.SiplicityService.CountRecords:input_type -> siplicity.v1.CountRecordsRequest
	12, // 27: siplicity.v1.SiplicityService.ListRecords:input_type -> siplicity.v1.ListRecordsRequest
	15, // 28: siplicity.v1.SiplicityService.GetRecord:input_type -> siplicity.v1.GetRecordRequest
	18, // 29: siplicity.v1.SiplicityService.PutRecord:input_type -> siplicity.v1.PutRecordRequest
	20, // 30: siplicity.v1.SiplicityService.UpdateRecord:input_type -> siplicity.v1.UpdateRecordRequest
	22, // 31: siplicity.v1.SiplicityService.UpdateField:input_type -> siplicity.v1.UpdateFieldRequest
	24, // 32: siplicity.v1.SiplicityService.LinkRecords:input_type -> siplicity.v1.LinkRecordsRequest
	26, // 33: siplicity.v1.SiplicityService.UnlinkRecords:input_type -> siplicity.v1.UnlinkRecordsRequest
	28, // 34: siplicity.v1.SiplicityService.Shutdown:input_type -> siplicity.v1.ShutdownRequest
	3,  // 35: siplicity.v1.SiplicityService.GetStatus:output_type -> siplicity.v1.GetStatusResponse
	5,  // 36: siplicity.v1.SiplicityService.PutFilePath:output_type -> siplicity.v1.PutFilePathResponse
	8,  // 37: siplicity.v1.SiplicityService.PutJob:output_type -> siplicity.v1.PutJobResponse
	10, // 38: siplicity.v1.SiplicityService.CountRecords:output_type -> siplicity.v1.CountRecordsResponse
	14, // 39: siplicity.v1.SiplicityService.ListRecords:output_type -> siplicity.v1.ListRecordsResponse
	17, // 40: siplicity.v1.SiplicityService.GetRecord:output_type -> siplicity.v1.GetRecordResponse
	19, // 41: siplicity.v1.SiplicityService.PutRecord:output_type -> siplicity.v1.PutRecordResponse
	21, // 42: siplicity.v1.SiplicityService.UpdateRecord:output_type -> siplicity.v1.UpdateRecordResponse
	23, // 43: siplicity.v1.SiplicityService.UpdateField:output_type -> siplicity.v1.UpdateFieldResponse
	25, // 44: siplicity.v1.SiplicityService.LinkRecords:output_type -> siplicity.v1.LinkRecordsResponse
	27, // 45: siplicity.v1.SiplicityService.UnlinkRecords:output_type -> siplicity.v1.UnlinkRecordsResponse
	29, // 46: siplicity.v1.SiplicityService.Shutdown:output_type -> siplicity.v1.ShutdownResponse
	35, // [35:47] is the sub-list for method output_type
	23, // [23:35] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_siplicity_v1_siplicity_proto_init() }
func file_siplicity_v1_siplicity_proto_init() {
	if File_siplicity_v1_siplicity_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_siplicity_v1_siplicity_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GetStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_siplicity_v1_siplicity_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GetStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_siplicity_v1_siplicity_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*PutFilePathRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_siplicity_v1_siplicity_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*PutFilePathResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_siplicity_v1_siplicity_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*Selection); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_siplicity_v1_siplicity_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*PutJobRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_siplicity_v1_siplicity_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*PutJobResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_siplicity_v1_siplicity_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*CountRecordsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_siplicity_v1_siplicity_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*CountRecordsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_siplicity_v1_siplicity_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*FieldPath); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_siplicity_v1_siplicity_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*ListRecordsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_siplicity_v1_siplicity_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*Field); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_siplicity_v1_siplicity_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*ListRecordsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_siplicity_v1_siplicity_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*GetRecordRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_siplicity_v1_siplicity_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*Metadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_siplicity_v1_siplicity_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*GetRecordResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_siplicity_v1_siplicity_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*PutRecordRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_siplicity_v1_siplicity_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*PutRecordResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_siplicity_v1_siplicity_proto_msgTypes[18].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateRecordRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_siplicity_v1_siplicity_proto_msgTypes[19].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateRecordResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_siplicity_v1_siplicity_proto_msgTypes[20].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateFieldRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_siplicity_v1_siplicity_proto_msgTypes[21].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateFieldResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_siplicity_v1_siplicity_proto_msgTypes[22].Exporter = func(v any, i int) any {
			switch v := v.(*LinkRecordsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_siplicity_v1_siplicity_proto_msgTypes[23].Exporter = func(v any, i int) any {
			switch v := v.(*LinkRecordsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_siplicity_v1_siplicity_proto_msgTypes[24].Exporter = func(v any, i int) any {
			switch v := v.(*UnlinkRecordsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_siplicity_v1_siplicity_proto_msgTypes[25].Exporter = func(v any, i int) any {
			switch v := v.(*UnlinkRecordsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_siplicity_v1_siplicity_proto_msgTypes[26].Exporter = func(v any, i int) any {
			switch v := v.(*ShutdownRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_siplicity_v1_siplicity_proto_msgTypes[27].Exporter = func(v any, i int) any {
			switch v := v.(*ShutdownResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_siplicity_v1_siplicity_proto_msgTypes[28].Exporter = func(v any, i int) any {
			switch v := v.(*FieldPath_Entry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_siplicity_v1_siplicity_proto_msgTypes[5].OneofWrappers = []any{}
	file_siplicity_v1_siplicity_proto_msgTypes[7].OneofWrappers = []any{}
	file_siplicity_v1_siplicity_proto_msgTypes[10].OneofWrappers = []any{}
	file_siplicity_v1_siplicity_proto_msgTypes[16].OneofWrappers = []any{}
	file_siplicity_v1_siplicity_proto_msgTypes[20].OneofWrappers = []any{}
	file_siplicity_v1_siplicity_proto_msgTypes[22].OneofWrappers = []any{}
	file_siplicity_v1_siplicity_proto_msgTypes[28].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_siplicity_v1_siplicity_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_siplicity_v1_siplicity_proto_goTypes,
		DependencyIndexes: file_siplicity_v1_siplicity_proto_depIdxs,
		EnumInfos:         file_siplicity_v1_siplicity_proto_enumTypes,
		MessageInfos:      file_siplicity_v1_siplicity_proto_msgTypes,
	}.Build()
	File_siplicity_v1_siplicity_proto = out.File
	file_siplicity_v1_siplicity_proto_rawDesc = nil
	file_siplicity_v1_siplicity_proto_goTypes = nil
	file_siplicity_v1_siplicity_proto_depIdxs = nil
}
