syntax = "proto3";

package siplicity.v1;

option go_package = "./;siplicityv1";

service SiplicityService {
  rpc GetStatus(GetStatusRequest) returns (GetStatusResponse) {}
  rpc PutFilePath(PutFilePathRequest) returns (PutFilePathResponse) {}
  rpc PutJob(PutJobRequest) returns (PutJobResponse) {}
  rpc CountRecords(CountRecordsRequest) returns (CountRecordsResponse) {}
  rpc CountFeatures(CountFeaturesRequest) returns (CountFeaturesResponse) {}
  rpc PreparedFeatureCount(PreparedFeatureCountRequest) returns (PreparedFeatureCountResponse) {}
  rpc ListRecords(ListRecordsRequest) returns (ListRecordsResponse) {}
  rpc GetRecord(GetRecordRequest) returns (GetRecordResponse) {}
  rpc PutRecord(PutRecordRequest) returns (PutRecordResponse) {}
  rpc UpdateRecord(UpdateRecordRequest) returns (UpdateRecordResponse) {}
  rpc UpdateField(UpdateFieldRequest) returns (UpdateFieldResponse) {}
  rpc LinkRecords(LinkRecordsRequest) returns (LinkRecordsResponse) {}
  rpc UnlinkRecords(UnlinkRecordsRequest) returns (UnlinkRecordsResponse) {}
  rpc Shutdown(ShutdownRequest) returns (ShutdownResponse) {}
}

message GetStatusRequest {
  int32 status = 1;
}

message GetStatusResponse {
  bool done = 1;
}

message PutFilePathRequest {
  string path = 1;
}

message PutFilePathResponse {
  int32 status = 1;
}

message Selection {
  repeated int32 id = 1;
}

message PutJobRequest {
  optional Selection selection = 1;
  optional string filter = 2; // TODO: change filter fields to query fields
  string action = 3; // TODO: change to enum
}

message PutJobResponse {
  int32 status = 1;
}

enum GraphType {
  GRAPH_TYPE_UNSPECIFIED = 0;
  GRAPH_TYPE_INPUT = 1;
  GRAPH_TYPE_OUTPUT = 2;
}

message CountRecordsRequest {
  optional int32 id = 1;
  optional GraphType graph = 2; // If graph isn't specified, check all records
  optional string filter = 3; // TODO: change filter fields to query fields
}

message CountRecordsResponse {
  int32 count = 1;
}

enum ReportType {
  REPORT_TYPE_UNSPECIFIED = 0;
  REPORT_TYPE_EXTENSIONS = 1;
  REPORT_TYPE_MODIFIED = 2;
  REPORT_TYPE_ZERO_BYTE = 3;
  REPORT_TYPE_DUPLICATES = 4;
  REPORT_TYPE_FORMAT_CLASS = 5;
  REPORT_TYPE_MIME_TYPE = 6;
  REPORT_TYPE_FILE_FORMAT = 7;
  REPORT_TYPE_UNKNOWN = 8;
  REPORT_TYPE_MULTIPLE_IDENTIFICATION = 9;
}

message PreparedFeatureCountRequest {
  ReportType report = 1;
  optional int32 max = 2;
}

message PreparedFeatureCountResponse {
  message Feature {
    string value = 1;
    int32 count = 2;
  }
  repeated Feature features = 1;
}

message CountFeaturesRequest {
  optional int32 id = 1;
  optional GraphType graph = 2; // If graph isn't specified, check all records
  optional FieldPath feature = 3; // TODO: change filter fields to query fields
}

message CountFeaturesResponse {
  message Feature {
    string value = 1;
    int32 count = 2;
  }
  repeated Feature features = 1;
}

message FieldPath {
  message Entry {
    optional string namespace = 1;
    string name = 2;
    optional string value = 3;
    optional int32 index = 4;
    optional Entry contains = 5;
  }
  repeated Entry entries = 1;
}

message ListRecordsRequest {
  optional int32 id = 1;
  optional GraphType graph = 2;
  optional string filter = 3;
  optional FieldPath display = 4;
  repeated FieldPath fields = 5;
}

enum RecordType {
  RECORD_TYPE_UNSPECIFIED = 0;
  RECORD_TYPE_SCHEMA = 1;
  RECORD_TYPE_ROOT = 2;
  RECORD_TYPE_FILE = 3;
  RECORD_TYPE_VIRTUAL_FILE = 4;
  RECORD_TYPE_DIRECTORY = 5;
  RECORD_TYPE_VIRTUAL_DIRECTORY = 6;
  RECORD_TYPE_ARCHIVE = 7;
  RECORD_TYPE_VIRTUAL_ARCHIVE = 8;
}

message Field {
  string namespace = 1;
  string name = 2;
  string value = 3;
}

message ListRecordsResponse {
  int32 id = 1;
  RecordType typ = 2;
  string name = 3;
  repeated Field fields = 4;
  repeated ListRecordsResponse children = 5;
}

message GetRecordRequest {
  int32 id = 1;
}

message Metadata {
  Field field = 1;
  repeated Metadata children = 2;
}

message GetRecordResponse {
  RecordType typ = 1;
  string path = 2;
  int64 size = 3;
  repeated Metadata metadata = 4;
}

message PutRecordRequest {
  optional int32 id = 1;
  optional GraphType graph = 2;
  GetRecordResponse record = 3;
}

message PutRecordResponse {
  int32 id = 1;
}

message UpdateRecordRequest {
  int32 id = 1;
  GetRecordResponse record = 2;
}

message UpdateRecordResponse {}

message UpdateFieldRequest {
  int32 id = 1;
  optional FieldPath path = 2;
  optional bool overwrite = 3;
  Field field = 4;
}

message UpdateFieldResponse {}

message LinkRecordsRequest {
  optional int32 id = 1;
  GraphType graph = 2;
  optional GraphType origin = 3;
  optional bool shift = 4;
  Selection records = 5;
}

message LinkRecordsResponse {}

message UnlinkRecordsRequest {
  GraphType graph = 1;
  Selection records = 2;
}

message UnlinkRecordsResponse {}

message ShutdownRequest {}

message ShutdownResponse {}
