name: Fetch and merge siplicity-foss branch from Siplicity
on:
  workflow_dispatch: # Allows you to run this manually
  schedule:
    - cron: '0 0 * * *'
permissions:
  contents: write
jobs:
  merge-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Current Repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Configure git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - name: Fetch and merge
        env:
          EXTERNAL_TOKEN: ${{ secrets.SIPLICITY_FOSS }}
        run: |
          git remote add upstream "https://x-access-token:${EXTERNAL_TOKEN}@github.com/sipli-city/siplicity.git"
          git fetch upstream siplicity-foss
          if ! git merge upstream/siplicity-foss --no-edit; then
            echo "::error::Merge conflict detected. Manual resolution required."
            git merge --abort
            exit 1
          fi
      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/sipli-city/siplicity-foss.git"
          git push origin main
